---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dphome
spec:
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-vl
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-vl
        configMap:
          name: cfm

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfm
data:
  index.html: |
    <html>
    <body>
      <h1>Hello Netology</h1>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: svcnginx
spec:
  selector:
    app: web-nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: netology1.mil
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svcnginx
            port: 
              number: 80
  tls:
    - hosts:
      - netology1.mil
      secretName: mysecret-tls